author: MDCollins
database: false
description: Updates the tab list with prefixes and afk status.
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: com.blockmovers.plugins.afkr.AFKr
name: AFKr
startup: postworld
url: http://blockmovers.com/
version: '0.1'
depend: [Vault]
commands:
  afkr:
    usage: /<command> (player)
    description: Lists afk players and for how long
permissions:
  afkr.exempt:
    default: false
    description: Cannot be kicked